### ISSUE TITLE
Incorrect data types in AsepriteNinePatchProperties

### ISSUE THREAD

**Issue by CloudMax94** [AristurtleDev/AsepriteDotNet#26]
### Description

This was fixed for the slice bounds in commit [52aa5a](https://github.com/AristurtleDev/AsepriteDotNet/commit/52aa5a) but appears that the same problem remains for the center bounds of AsepriteNinePatchProperties.

### Steps to Reproduce

Create a 32x32 sprite with a 9-slice of bound (0, 0, 32, 32) and 9-slices bounds to (3, 3, 26, 26)

### Expected Behavior

Get (3, 3, 26, 26) from the CenterBounds of a NinePatchSlice

### Actual Behavior

Get (3, 3, 14, 139296) from the CenterBounds of a NinePatchSlice

**Comment by AristurtleDev** [comment]
Sorry I haven't fixed this yet @CloudMax94, but haven't forgotten. Been focused on a paid contract for another repository.

**Comment by AristurtleDev** [comment]
This has been resolved  in PR #29
Version 1.8.0 should be available on NuGet shortly once it finishes indexing there @CloudMax94
